; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<*>
    -<button_test.cpp>

upload_port = COM9
monitor_port = COM9
upload_speed = 921600

lib_deps =
    T-vK/ESP32 BLE Keyboard
    rfetick/MPU6050_light
    mathertel/OneButton

[env:esp32dev_button_test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

upload_port = COM9
monitor_port = COM9
upload_speed = 921600

build_src_filter =
    -<*>
    +<button_test.cpp>

lib_deps =
    mathertel/OneButton

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_flags =
    -std=gnu++17
    -D PIO_UNIT_TESTING
    -I test/test_error_logic
build_src_filter =
    -<*>
    +<errors.cpp>

[env:esp32dev_mpu_fail]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -D INJECT_MPU_INIT_FAIL
lib_deps =
    T-vK/ESP32 BLE Keyboard
    rfetick/MPU6050_light
    mathertel/OneButton

[env:esp32dev_ble_fail]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -D INJECT_BLE_DISCONNECT
lib_deps =
    T-vK/ESP32 BLE Keyboard
    rfetick/MPU6050_light
    mathertel/OneButton

[env:esp32dev_bad_calibration]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -D INJECT_BAD_CALIBRATION_CAPTURE
lib_deps =
    T-vK/ESP32 BLE Keyboard
    rfetick/MPU6050_light
    mathertel/OneButton

[env:esp32dev_invalid_calibration]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -D INJECT_INVALID_CALIBRATION_DATA
lib_deps =
    T-vK/ESP32 BLE Keyboard
    rfetick/MPU6050_light
    mathertel/OneButton
